## Numpy array and basic

In [1]:
import numpy as np
import time

## creating array in list

In [2]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D array: ", arr_1d)
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array: ", arr_2d)

1D array:  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]


### List vs numpy array

In [3]:
py_list = [1, 2, 3]
print("Python list multiplication", py_list * 2)

np_array = np.array([1, 2, 3]) # element wise multiplication
print("Python array multiplication", np_array * 2)

start = time.time()
py_list = [i * 2 for i in range(10000000)]
print("\n List operation time:", time.time() - start)

start = time.time()
np_array = np.arange(10000000) * 2
print("\n numpy operation time:", time.time() - start)

Python list multiplication [1, 2, 3, 1, 2, 3]
Python array multiplication [2 4 6]

 List operation time: 0.9582452774047852

 numpy operation time: 0.06455850601196289


## Creating array from scratch

In [4]:
zeros = np.zeros((3, 4))
print("zero array: \n", zeros)

ones = np.ones((2, 3))
print("ones array: \n", ones)

full = np.full((2,2), 7)
print("full array: \n", full)

random = np.random.random((2, 3))
print("random array: \n", random)

sequence = np.arange(0, 10, 2)
print("sequnce array: \n", sequence)

zero array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]
random array: 
 [[0.90945798 0.04447693 0.85944286]
 [0.01292907 0.25830934 0.4628842 ]]
sequnce array: 
 [0 2 4 6 8]


### Vector, Matrix and Tensor

In [5]:
vector = np.array([1, 2, 3])
print("Vector: ", vector)

matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("Matrix: ", matrix)

tensor = np.array([[[1, 2], [3, 4]],
                   [[5, 6], [7, 8]]])
print("Tensor: \n", tensor)


Vector:  [1 2 3]
Matrix:  [[1 2 3]
 [4 5 6]]
Tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array properties

In [6]:
arr = np.array([[1,2,3],
               [4, 5, 6]])
print("Shape", arr.shape)
print("Dimension", arr.ndim)
print("Size", arr.size)
print("Datatype", arr.dtype)

Shape (2, 3)
Dimension 2
Size 6
Datatype int64


### Array Reshaping

In [7]:
arr = np.arange(12)
print("original array:", arr)

reshaped = arr.reshape((3, 4))
print("\n Reshaped array:", reshaped)

flattened = reshaped.flatten()
print("\n Flattened array:", flattened)

# ravel (returns view, insteed of copy)
raveled = reshaped.ravel()
print("\n raveled array:", raveled)

# Transpose
transpose = reshaped.T
print("\n Transposed array: \n", transpose)


original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed array: 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
