# Numpy Array Operations

In [2]:
import numpy as np

## Slicing and Indexing

In [3]:
arr = np.array([1, 2, 3, 4, 5, 6 ,7, 8, 9, 10])
print("Basic Slicing", arr[2:7])
print("With step Slicing", arr[1:8:2])
print("Nagitive indexing", arr[-2])

Basic Slicing [3 4 5 6 7]
With step Slicing [2 4 6 8]
Nagitive indexing 9


In [4]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("Spacific element", arr_2d[1, 2])
print("Entire row: ", arr_2d[1]) #  <----row target
print("Entire row: ", arr_2d[:, 1]) #  <----column target

Spacific element 6
Entire row:  [4 5 6]
Entire row:  [2 5 8]


## Sorting

In [5]:
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print("Sorted Array", np.sort(unsorted))

arr_2d_unsorted = np.array([[3, 1], [1, 2], [2, 3]])
print("Sorted 2D array by column \n", np.sort(arr_2d_unsorted, axis = 0))
print("Sorted 2D array by row \n", np.sort(arr_2d_unsorted, axis = 1))

Sorted Array [1 1 2 3 4 5 6 9]
Sorted 2D array by column 
 [[1 1]
 [2 2]
 [3 3]]
Sorted 2D array by row 
 [[1 3]
 [1 2]
 [2 3]]


## Filter

In [6]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_number = numbers[numbers % 2 == 0]
print("Even number", even_number)

Even number [ 2  4  6  8 10]


### Filter with mask 

In [7]:
mask = numbers > 5
print("Number greater than 5 ", numbers[mask])

Number greater than 5  [ 6  7  8  9 10]


## Fancy indexing vs np.whare()

In [8]:
indices = [0, 2, 4]
print(numbers[indices])

where_result = np.where(numbers >5)
print(where_result)
print("NP where", numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where [ 6  7  8  9 10]


In [9]:
condition_array = np.where(numbers > 5, "true", "False")
print(condition_array)

['False' 'False' 'False' 'False' 'False' 'true' 'true' 'true' 'true'
 'true']


in cell 8 np.where is like: \
if(condition){ \
    true \
} \
else{false} 

### Adding and removing data

In [10]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
"""
combine = arr1 + arr2
print(combine)   # it gives the addition Output ---> [5 7 9]
"""
combine = np.concatenate((arr1, arr2))
print(combine)

[1 2 3 4 5 6]


### array compatibillty

In [11]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6, 7])

print("compatibillty shapes", a.shape == b.shape)

compatibillty shapes False


In [12]:
original = np.array([[1, 2], [3, 4]])
new_row = np.array(([5, 6]))
print("Original \n", original)
with_new_row = np.vstack((original, new_row))  # always add new row (always laft to right) it is vertical stack
print("with new row \n", with_new_row)

new_col = np.array([[7], [8]])
with_new_col = np.hstack((original, new_col))
print("with new column \n", with_new_col)

Original 
 [[1 2]
 [3 4]]
with new row 
 [[1 2]
 [3 4]
 [5 6]]
with new column 
 [[1 2 7]
 [3 4 8]]


In [13]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
deleted = np.delete(arr, 2)
print("Array after deletion:", deleted)

Array after deletion: [1 2 4 5 6 7 8 9]
